### ISSUE TITLE
Strange icon when no window (Fedora 39)

### ISSUE THREAD

**Issue by Shogu** [fablevi/OnTheTop#4]
Hi!

Thanks for this great & smart extension!

Everything works very well but when i am on the desktop with NO window, the icon turn into a strange one : 

![Capture d’écran du 2024-06-17 21-17-00](https://github.com/fablevi/OnTheTop/assets/696880/e0529410-0f00-48d9-8264-44987fed2f4f)

Is it expected? If yes, is there any way to edit the extension into my system to modify it?

Thanks a lot.

Greetings from France

Ogu

**Comment by fablevi** [comment]
Hey, so this will come up if there is no window, or gnome shell doesnt see any active window :)

**Comment by fablevi** [comment]
Right now if you want to edit the icons you need to locate the  extension folder and change the icon theme,  probably in the future, i will ad an extra settings to change icons :)

**Comment by Jenyyk** [comment]
i know this issue is closed, but could i ask why this icon specifically has mostly white?
like why not make the inside white and the background transparent?
i tried reversing it and it looks much better:

![Image](https://github.com/user-attachments/assets/38b5102d-74fb-4b72-a9ca-3aab7eda1589)
Here is the .svg code if anyone is interested:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-1.5024 -15.5024 16 16">
	<path d="m1.904-2.904a6.5 6.5 90 109.192-9.192A6.5 6.5 90 101.904-2.904zm2.194-.523 6.475-6.475A4.73 4.73 90 014.098-3.427zm4.804-8.146-6.475 6.475a4.73 4.73 90 016.475-6.475" fill="#000000"/>
</svg>
```
All you need to do is replace the `noFocus-symbolic.svg` icon in
`~/.local/share/gnome-shell/extensions/OnTheTop@fablevi.github.io/icons`
